apps:
  - name: flask
    type: Deployment
    replicaCount: 1
    image:
      repository: majavier/stensul-flask
      tag: latest
    service:
      type: LoadBalancer
      port: 80
      targetPort: 5000
    env:
      MYSQL_HOST: stensul-app-mysql
      MYSQL_DATABASE: stensul
      MYSQL_USER: stensul
      MYSQL_PASSWORD: Password123!

  - name: mysql
    type: StatefulSet
    replicaCount: 1
    image:
      repository: majavier/stensul-mysql
      tag: latest
    service:
      type: ClusterIP
      port: 3306
    volumeMounts:
      mountPath: /var/lib/mysql
    storage:
      size: 1Gi
    env:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: stensul
      MYSQL_USER: stensul
      MYSQL_PASSWORD: Password123!