{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.targetPort | default .service.port }}
  selector:
    app: {{ $.Release.Name }}-{{ .name }}
---
{{- end }}